assistant:
  port: 8898
  host: 0.0.0.0
  wav-file-name: record.wav

  config:
    path: config
    includePath: 
      - config/user
  
  output:
    mode: voice
  
  input:
    mode: text
    position: local
  
voices:
  channels: 2
  rate: 44100
  engine:

jieba:
  cut_all: true




    