Device2:
  keywords:
    - 二号灯
  type: ExternalDevice
  instruction: 这是二号灯
  host: 192.168.0.1
  port: 8888

微信:
  type: Window
  instruction: 我可以操作微信哦

Typora:
  keywords:
    - 笔记
  execPath: F:\Typora\Typora.exe
  type: Software
  instruction: 我现在可以操作笔记了哦



  

