MetaModule:
  operations:
    -
      keys:
        - 说明
      method: self.show_instruction
      
Window:
  operations:
    -
      keys:
        - 窗口
        - 界面
      operations:
        -
          keys:
            - 显示
            - 正常化
            - 打开
          method: self.window_show
        - 
          keys:
            - 隐藏
            - 最小化
          method: self.window_hide
        -
          keys:
            - 最大化
            - 放大
          method: self.window_maximize
        - 
          keys:
            - 关闭
            - 退出
          method: self.window_exit

Puppy:
  operations:
    - 
      keys:
        - 音量
        - 声音
      operations:
        -
          keys:
            - 提高
          method: self.volume_up
        -
          keys:
            - 降低
          method: self.volume_down
    -
      keys:
        - 语速
      operations:
        - 
          keys:
            - 加快
            - 提高
          method: self.rate_up
        - 
          keys:
            - 降低
            - 减慢
          method: self.rate_down

Software:
  operations:
    - 
      keys:
        - 启动
      method: self.launch
    - 
      keys:
        - 输入
        - 写
      method: self.sendText
    - 
      keys:
        - 全选
      shotkeys:
        - '^a'
      

Camera:
  operations:
    - 
      keys:
        - 启动
      method: self.launch
    - 
      keys:
        - 退出
      method: self.exit
    - 
      keys:
        - 拍照
      method: self.shot
    - 
      keys:
        - 识别
        - 检测
      operations:
        - 
          keys:
            - 手势
          operations:
            - 
              keys:
                - 打开
                - 启动
              method: self.open_detector_hands
            -
              keys:
                - 关闭
                - 退出
              method: self.stop_detector_hands
        - 
          keys:
            - 人脸
            - 面部
          operations:
            - 
              keys:
                - 打开
                - 启动
              method: self.open_detector_face_mesh
            -
              keys:
                - 关闭
                - 退出
              method: self.stop_detector_face_mesh
          

PowerPoint:
  operations:
    - 
      keys:
        - 新建
      shotkeys:
        - '^n'
        - '%n'
        - 'l'
        - '1'
    - 
      keys:
        - 最近
      operations:
        - 
          keys:
            - 打开
          shotkeys:
            - '%h'
            - 'y'
            - 'f'
    - 
      keys:
        - 放映
      operations:
        - 
          keys:
            - 开始
          shotkeys:
            - '{F5}'
    -
      keys:
        - 下一页
        - 下一张
      shotkeys:
        - '{DONW}'
    -
      keys:
        - 上一页
        - 上一张
      shotkeys:
        - '{UP}'

Website:
  operations:
    - 
      keys:
        - 搜索
      method: self.search
    -
      keys:
        - 打开
      method: self.open

Typora:
  operations:
    - 
      keys:
        - 删除
      shotkeys:
        - '{BS}'
    - 
      keys:
        - 跳转
      operations:
        - 
          keys:
            - 行首
          shotkeys:
            - '^{HOME}'
        - 
          keys:
            - 行末
            - 文末
          shotkeys:
            - '^{END}'
    - 
      keys:
        - 选择
      operatiaons:
        - 
          keys:
            - 当前
          shotkeys:
            - '^l'
    - 
      keys:
        - 视图
      operations:
        - 
          keys:
            - 切换
          operations:
            - 
              keys:
                - 大纲
              shotkeys:
                - '^+1'
            - 
              keys:
                - 文件列表
              shotkeys:
                - '^+2'
    -
      keys:
        - 格式
      operations:
        - 
          keys:
            - 加粗
          shotkeys:
            - '^b'
        - 
          keys:
            - 斜体
          shotkeys:
            - '^i'
        - 
          keys:
            - 下划线
          shotkeys:
            - '^u'
        - 
          keys:
            - 代码
          shotkeys:
            - '^+`'
        - 
          keys:
            - 删除线
          shotkeys:
            - '%+5'
        - 
          keys:
            - 清除
          shotkeys:
            - '^\'
    - 
      keys:
        - 标题
      operations:
        - 
          keys:
            - 一级
          shotkeys:
            - '^1'
        - 
          keys:
            - 二级
          shotkeys:
            - '^2'
        - 
          keys:
            - 三级
          shotkeys:
            - '^3'
        - 
          keys:
            - 四级
          shotkeys:
            - '^4'
        - 
          keys:
            - 五级
          shotkeys:
            - '^5'
        - 
          keys:
            - 六级
          shotkeys:
            - '^6'
    -
      keys:
        - 列表
      operations:
        - 
          keys:
            - 有序
          shotkeys:
            - '^+['
        - 
          keys:
            - 无序
          shotkeys:
            - '^+]'
    -
      keys:
        - 引用
      shotkeys:
        - '^+q'
    -
      keys:
        - 段落
      shotkeys:
        - '^0'
            
Light:
  operations:
    -
      keys:
        - 打开
      method: self.open

        

      
