MetaModule:
  operations:
    -
      keys:
        - 说明
      method: self.show_instruction
      
Window:
  operations:
    -
      keys:
        - 窗口
        - 界面
      operations:
        -
          keys:
            - 显示
            - 正常化
            - 打开
          method: self.window_show
        - 
          keys:
            - 隐藏
            - 最小化
          method: self.window_hide
        -
          keys:
            - 最大化
            - 放大
          method: self.window_maximize
        - 
          keys:
            - 关闭
            - 退出
          method: self.window_exit

Puppy:
  operations:
    - 
      keys:
        - 音量
        - 声音
      operations:
        -
          keys:
            - 提高
          method: self.volume_up
        -
          keys:
            - 降低
          method: self.volume_down
    -
      keys:
        - 语速
      operations:
        - 
          keys:
            - 加快
            - 提高
          method: self.rate_up
        - 
          keys:
            - 降低
            - 减慢
          method: self.rate_down

Software:
  operations:
    - 
      keys:
        - 启动
      method: self.launch

Camera:
  operations:
    - 
      keys:
        - 启动
      method: self.launch
    - 
      keys:
        - 退出
      method: self.exit
    - 
      keys:
        - 拍照
      method: self.shot
    - 
      keys:
        - 识别
        - 检测
      operations:
        - 
          keys:
            - 手势
          operations:
            - 
              keys:
                - 打开
                - 启动
              method: self.open_detector_hands
            -
              keys:
                - 关闭
                - 退出
              method: self.stop_detector_hands
        - 
          keys:
            - 人脸
            - 面部
          operations:
            - 
              keys:
                - 打开
                - 启动
              method: self.open_detector_face_mesh
            -
              keys:
                - 关闭
                - 退出
              method: self.stop_detector_face_mesh
          

PowerPoint:
  operations:
    - 
      keys:
        - 新建
      shotkeys:
        - '^n'
        - '%n'
        - 'l'
        - '1'
    - 
      keys:
        - 最近
      operations:
        - 
          keys:
            - 打开
          shotkeys:
            - '%h'
            - 'y'
            - 'f'
    - 
      keys:
        - 放映
      operations:
        - 
          keys:
            - 开始
          shotkeys:
            - '{F5}'
    -
      keys:
        - 下一页
        - 下一张
      shotkeys:
        - '{DONW}'
    -
      keys:
        - 上一页
        - 上一张
      shotkeys:
        - '{UP}'

Website:
  operations:
    - 
      keys:
        - 搜索
      method: self.search
    -
      keys:
        - 打开
      method: self.open

