MetaModule:
  operations:
    -
      keys:
        - 说明
      method: self.show_instruction
      
Window:
  operations:
    -
      keys:
        - 窗口
        - 界面
      operations:
        -
          keys:
            - 显示
            - 正常化
            - 打开
          method: self.window_show
        - 
          keys:
            - 隐藏
            - 最小化
          method: self.window_hide
        -
          keys:
            - 最大化
            - 放大
          method: self.window_maximize
        - 
          keys:
            - 关闭
            - 退出
          method: self.window_exit

Puppy:
  operations:
    - 
      keys:
        - 音量
        - 声音
      operations:
        -
          keys:
            - 提高
          method: self.volume_up
        -
          keys:
            - 降低
          method: self.volume_down
    -
      keys:
        - 语速
      operations:
        - 
          keys:
            - 加快
            - 提高
          method: self.rate_up
        - 
          keys:
            - 降低
            - 减慢
          method: self.rate_down

Software:
  operations:
    - 
      keys:
        - 启动
        - 打开
      method: self.launch

Camera:
  operations:
    - 
      keys:
        - 启动
        - 打开
      method: self.launch
    - 
      keys:
        - 关闭
        - 退出
      method: self.exit
    - 
      keys:
        - 拍照
      method: self.shot


